### PR TITLE
Fix title of README

### PR DESCRIPTION
**Pull request by drewnoakes**

### CODE REVIEW

**Comment by drewnoakes** [comment]
This PR is mostly just a way to ask a question :)

Have you intentionally disabled the issue tracker here? Are you monitoring the upstream one? I'm currently using a paid-for extension that allows multiple carets, and it has a few features that would stop me from using this extension just yet. I'd like to capture those differences in an issue somewhere.

**Comment by drewnoakes** [comment]
Also it'd be great if you could answer the questions about the tools you use for zooming/snipping in the comments on your recent Channel 9 video!

https://channel9.msdn.com/Shows/Visual-Studio-Toolbox/Mads-Kristensen-Extensions

**Comment by drewnoakes** [comment]
Cheers. Didn't know <kbd>Win</kbd>+<kbd>+</kbd> did that. Very cool.

You briefly showed a screenshot tool that looked very nice. Mind telling what that was too?

**Comment by madskristensen** [comment]
That was LightShot I think it's called

**Pull request merged**
